import './globals.css';

import { Inter } from 'next/font/google';
import { auth } from '@/auth';
import { TRPCReactProvider } from '@/trpc/react';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { SessionProvider } from 'next-auth/react';
import { twMerge } from 'tailwind-merge';

import { EdgeStoreProvider } from '@/lib/edgestore';
import { ToastContainer } from '@/hooks/useToast';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={twMerge(inter.className, 'flex justify-center')}>
          <TRPCReactProvider>
            <EdgeStoreProvider>{children}</EdgeStoreProvider>
            {/* <ReactQueryDevtools initialIsOpen={false} /> */}
          </TRPCReactProvider>
          <ToastContainer />
        </body>
      </html>
    </SessionProvider>
  );
}
